markdown: rdiscount
permalink: /:title/
url: http://mugbya.github.io
name: Mugbya's Blog
author: mugbya
email: mugbya@gmail.com
duoshuo: mugbya
cnzz: 119959
github: mugbya
pygments: true
safe: true
paginate: 20

